### ISSUE TITLE
Adding Custom Provider

### ISSUE THREAD

**Issue by nurseymybush** [oauth-io/oauth-ios#10]
I was wondering how to add a custom provider, specifically implementing Fitbit OAuth2.0 myself. Is there any documentation on this process? Thanks

**Comment by thyb** [comment]
Take a look at this link: http://docs.oauth.io/#adding-providers-to-oauth-io

All existing providers are implemented here: https://github.com/oauth-io/oauthd/tree/master/providers

Once you’ve implemented your provider, you can test it using oauthd, the opensource version of OAuth.io and then, just make a pull request and we’ll merge it into OAuth.io as soon as we can.
