### ISSUE TITLE
Swift 2.3/3.0 support

### ISSUE THREAD

**Issue by ghvg1313** [oauth-io/oauth-ios#15]
As I'm using XCode 8.0 GM seed compiling oauth.io module against Swift 2.3, it complains `Use of undeclared type 'OAuthIORequest'`, in fact compiler can't find any reference to the class defined inside the module. Everything works fine under XCode 7, Swift 2.2

**Comment by bumpmann** [comment]
Done !

I pushed it as 1.2.2 on pod so we can `pod repo update` / `pod update`

I also updated the exemple with swift 3:
https://github.com/oauth-io/ios-swift-example
